[package]
name = "toastty-io"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
libc = "0.2"
mio = { workspace = true, features = ["os-poll", "os-ext"] }
tracing.workspace = true
winit.workspace = true

[dev-dependencies]
toastty-pty.workspace = true

[lints]
workspace = true
